# Generated by Django 4.0.4 on 2022-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='company',
            field=models.CharField(max_length=800, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='destination',
            field=models.CharField(max_length=800, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='origin',
            field=models.CharField(max_length=800, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='signature_mode',
            field=models.CharField(max_length=800, verbose_name='Signature Mode'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='status',
            field=models.CharField(max_length=800, verbose_name='Status'),
        ),
    ]
